name: Build RNS Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - main
        arch:
          - mips_24kc

    steps:
      - uses: actions/checkout@v4

      - name: Create directories
        run: mkdir artifacts feed

      - name: Build packages
        uses: gretel/openwrt-packager@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          EXTRA_FEEDS: src-git|reticulum|https://github.com/gretel/feed-reticulum.git
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: rns

      - name: Verify build outputs
        run: |
          echo "Checking for built packages..."
          find "${{ github.workspace }}/artifacts" \( -name '*.ipk' -o -name '*.apk' \) \
            -type f -printf '%p (%s bytes)\n'

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.release }}-packages
          path: |
            artifacts/bin/packages/${{ matrix.arch }}/packages/*.ipk
            artifacts/bin/packages/${{ matrix.arch }}/packages/*.apk
          if-no-files-found: error
